"""Package extension/ into claude-for-libreoffice.oxt (an .oxt is a zip), and write update.xml,
the feed LibreOffice's Tools > Extensions > Check for Updates reads (description.xml points at it
on main)."""

import os
import re
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "extension")
OUT = os.path.join(HERE, "claude-for-libreoffice.oxt")
FEED = os.path.join(HERE, "update.xml")
DOWNLOAD = "https://raw.githubusercontent.com/Willykil/libreoffice-claude/main/claude-for-libreoffice.oxt"


def version():
    with open(os.path.join(SRC, "description.xml"), encoding="utf-8") as f:
        return re.search(r'<version value="([^"]+)"', f.read()).group(1)


def feed():
    return """<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by build.py from extension/description.xml; don't edit by hand. -->
<description xmlns="http://openoffice.org/extensions/update/2006"
             xmlns:xlink="http://www.w3.org/1999/xlink">
  <identifier value="org.willykil.claude"/>
  <version value="%s"/>
  <update-download>
    <src xlink:href="%s"/>
  </update-download>
</description>
""" % (version(), DOWNLOAD)


def build(out=OUT, feed_out=FEED):
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        for root, dirs, files in os.walk(SRC):
            dirs[:] = sorted(d for d in dirs if d != "__pycache__")
            for name in sorted(files):
                path = os.path.join(root, name)
                z.write(path, os.path.relpath(path, SRC).replace(os.sep, "/"))
    with open(feed_out, "w", encoding="utf-8", newline="\n") as f:
        f.write(feed())
    return out


if __name__ == "__main__":
    print(build())
